import { exec as _exec } from 'child_process'
import fs from 'fs/promises'
import packageJson from '../package.json'

function exec(command: string): Promise<string> {
  return new Promise((resolve, reject) => {
    _exec(command, (err, stdout, stderr) => {
      if (err) {
        reject(err)
      } else {
        resolve(stdout)
      }
    })
  })
}

const hash = await exec('git rev-parse HEAD')
const version = packageJson.version

const content = String.raw`
// This file is automatically generated. Do not edit.

export const COMMIT_HASH = '${hash.trim()}'
export const VERSION = '${version}'
export const API_VERSION = 1
export const BUILD_TIME = new Date(${Date.now()})
`

await fs.writeFile('lib/buildinfo.ts', content)
